{% set name = "scanpy" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

source:
  url: https://github.com/theislab/scanpy/archive/{{ version }}.tar.gz
  sha256: a479835bd58924682ac17e73755dc4008d7c5398816163da768b42ac3ab45c50
  patches:
    - patch

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - anndata >=0.6.22rc1
    - h5py !=2.10.0
    - importlib_metadata >=0.7
    - joblib
    - louvain
    - matplotlib ==3.0.*
    - natsort
    - networkx
    - numba >=0.41.0
    - pandas >=0.21
    - patsy
    - pytables
    - python >=3.6
    - scikit-learn >=0.21.2
    - scipy >=1.3
    - seaborn
    - statsmodels >=0.10.0rc2
    - tqdm
    - umap-learn >=0.3.0

test:
  imports:
    - scanpy

about:
  home: https://scanpy.readthedocs.io/en/latest/
  license: BSD-3
  summary: Single-Cell Analysis in Python. Scales to >1M cells. 

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
