{% set name = "LiBis_moabs" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "f27db964fd7555b3f5f38de49eab3d73340a6cf1f73d1fac3cbde6539c4a8b32"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - cycler
    - kiwisolver
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyparsing
    - pysam
    - python
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - seaborn
    - six
    - sklearn
    - utils
  run:
    - cycler
    - kiwisolver
    - matplotlib
    - numpy
    - pandas
    - pyparsing
    - pysam
    - python
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - seaborn
    - six
    - sklearn
    - utils

test:
  imports:
    - LiBis

about:
  home: "https://github.com/Dangertrip/LiBis"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Low input Bisulfite sequencing alignment"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
