{% set name = "LiBis_moabs" %}
{% set version = "0.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 80fdbdbb24a8b1c23ba4d62798ecd24dae5a60d39c84c63da14b5a6d080aaebc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy
    - pandas
    - pip
    - pysam
    - python >=3
    - scikit-learn
    - scipy
    - seaborn
  run:
    - matplotlib
    - numpy
    - pandas
    - pysam
    - python
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - LiBis
  commands:
    - LiBis --help

about:
  home: "https://github.com/Dangertrip/LiBis"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Low input Bisulfite sequencing alignment"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - dangertrip 
