{% set name = "LiBis_moabs" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: fe1feae769ac8ff8f4d743253fee1aef417b9eb229ed054387831c51af5deed6

build:
  number: 0
  entry_points:
    - LiBis=LiBis.libis:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - cycler
    - matplotlib
    - numpy
    - pandas
    - pyparsing
    - pysam
    - python
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - seaborn
    - six

test:
  imports:
    - LiBis
  commands:
    - LiBis --help

about:
  home: "https://github.com/Dangertrip/LiBis"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Low input Bisulfite sequencing alignment"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - dangertrip
