package:
  name: discosnp
  version: '2.4.2'

source:
  url: "https://github.com/GATB/DiscoSnp/releases/download/v2.4.2/DiscoSNP.-v2.4.2-Source.tar.gz"
  sha256: "c97e144a11eb87f2722402e84f3ee1f39e8804bf95ade561ac9bacb694d2f01f"

build:
  number: 0
  # requires clang>=4.5
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - zlib
  run:
    - zlib
    - bwa
    - shortreadconnector
    - python >=3.0

test:
  commands:
    - run_discoSnp++.sh -h
    - run_discoSnpRad.sh -h

about:
  home: https://gatb.inria.fr/software/discosnp/
  license: GNU Affero General Public License v3.0
  summary: Designed for discovering all kinds of SNPs

extra:
  identifiers:
    - biotools:discosnp
    - doi:10.1093/nar/gkn000
